---
title: "AKKSAM: Example"
author: "Nicolas Carrizosa Arias"
format: 
  html:
    toc: true        
    toc-depth: 4     
    toc-location: left  
    self-contained: true
---

# Functions

## Libraries

```{r library, warning = FALSE, message = FALSE}
# Required Packages
packages <- c(
  "dplyr", "Matrix", "splines", "corpcor",  # Essential dependencies
  "ggplot2", "patchwork"                    # Miscellaneous dependencies
)

# Install and/or load the packages
for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
```

## AKKSAM

```{r AKSSAM, warning = FALSE, message=FALSE}
# AKSSAM
source("AKSSAM.R")
```


# Univariate Gaussian Response

```{r}
## Simulate the data
set.seed(12345)                              # Set seed for reproducibility
m = 1                                        # Nº of covariates
n = 500                                      # Nº of instances
x <- runif(n, 0, 1)                          # Sampled covariate
X = as.matrix(x)                             
f = sqrt(x * (1 - x)) * sin((2 * pi * (1 + 2^(-3/5))) / (x + 2^(-3/5)))     # True effect 
f = f - mean(f)
FF = as.matrix(f)
y = f + rnorm(n, 0, sd = (0.3 * x + 0.2 * sqrt(x))^2)                   # Response


## AKSSAM 
model = AKSSAM(X = X, y = y, family = "gaussian", 
               lambda.init = rep(0.1, m), ndx = rep(60, m), bdeg = rep(3, m), 
               maxiter1 = 100, maxiter2 = 100, maxiter3 = 200, 
               tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, 
               epsilon = 1e-5)


## Obtain the estimated sets of knots and coefficients
K_sel = model$K_sel                   # Selected knots
Design_list = model$New_Design_list   # Design matrices
alpha = model$alpha.new               # Coefficients
B_star <- do.call(cbind, Design_list) # Joint design matrix B*
predictions <- B_star %*% alpha       # Predictions in X

## Make predictions and independent effects in any 
# Initialize terms
Design_list = vector("list", m + 1)
Design_list[[1]] = matrix(1, 100, 1) 
basis_length = rep(0,m)
covariate_predictions = vector("list", m)
bdeg = rep(3, m)
# Iterate through covariates
for (t in 1:m){
  # Build the design matrix with selected knots
  B = my.bbase4(seq(0,1, length.out = 100), K_sel[[t]], bdeg[t])
  Design_list[[t+1]] = B
  basis_length[t] = dim(B)[2]
  if (t == 1){index_0 = 2; index_1 = 1 + basis_length[1]
  }else{index_0 = 2 + sum(basis_length[1:(t-1)]); index_1 = index_0 + basis_length[t] - 1}
  # Effect of the t-th covariate
  covariate_predictions[[t]] = B %*% alpha[index_0:index_1]
}
# Entire prediction
B_star <- do.call(cbind, Design_list) # Joint design matrix B*
predictions <- B_star %*% alpha     


## Plot the results
plot_list <- lapply(1:m, function(i) {
  
  # Order the X values
o <- order(X[, i])

# True effect
data <- data.frame( 
  x = X[o, i], 
  y = y[o]
)

# Estimated effect
predicts <- data.frame( 
  x = seq(0, 1, length.out = 100),
  pred = covariate_predictions[[i]]
)

# Interior knots only
knots_use <- K_sel[[i]][-c(
  1, 2, 3, 4,
  length(K_sel[[i]])-3, length(K_sel[[i]])-2,
  length(K_sel[[i]])-1, length(K_sel[[i]])
)]

# Rug positioning
rng  <- range(data$y, na.rm = TRUE)
ymin <- rng[1]
ymax <- rng[2]
yrng <- ymax - ymin

y_base <- ymin - 0.40 * yrng
dy     <- 0.07 * yrng
offset <- 0.01 * yrng

rug_df <- data.frame(
  x    = knots_use,
  ymin = y_base + offset,
  ymax = y_base + dy + offset
)

plot <- ggplot() +
  geom_point(
    data = data,
    aes(x, y),
    shape = 21,
    fill = "grey",
    color = "grey60",
    size = 2,
    stroke = 0.8
  ) +
  geom_line(
    data = predicts,
    aes(x, pred),
    linewidth = 2.5,
    alpha = 0.8,
    color = "#1E88E5"
  ) +
  # Rug (knots)
  geom_segment(
    data = rug_df,
    aes(x = x, xend = x, y = ymin, yend = ymax),
    color = "#D81B60",
    linewidth = 3
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "grey85"),
    plot.margin = margin(10, 10, 10, 10)
  )

return(plot)

})

plot_list[[1]]
```
