---
title: "AKSSAM: Simulation 1 - SpaHet"
author: "Nicolas Carrizosa Arias"
format: 
  html:
    toc: true        
    toc-depth: 4     
    toc-location: left  
    self-contained: true
---

# Functions

## Libraries

```{r library, warning = FALSE, message=FALSE}
# Required Packages
packages <- c(
  "dplyr", "Matrix", "splines", "corpcor",  # AKSSAM: Essential dependencies
  "mgcv",                                   # P-splines dependencies
  "pso",                                    # PSO dependencies
  "splines2", "aspline",                    # A-splines dependencies
  "caret", "ggplot2", "grid", "gridExtra", "gridGraphics", "patchwork", "pROC",
  "pracma", "tidyverse", "xtable", "cowplot", "scales"
)

# Install and/or load the packages
for (pkg in packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
  library(pkg, character.only = TRUE)
}
```

## AKKSAM

```{r AKSSAM, warning = FALSE, message=FALSE}
# AKSSAM
source("Required_Scripts/AKSSAM.R")
```

## OKPSO

```{r PSO, warning = FALSE, message=FALSE}
# PSO
source("Required_Scripts/ok_gam.R")
```

# Data

The simulated data consists on the function 
$$f(x) = \sqrt{x(1-x)}\sin{\left(2\pi\cdot \frac{1+2^{-3/5}}{x+2^{-3/5}}\right)}$$

Function to simulate the data given the sample size and the SNR.

```{r}
simulate.data.1 <- function(n, SNR){
  
  # True response
  f <- function(x) sqrt(x * (1 - x)) * sin((2 * pi * (1 + 2^(-3/5))) / (x + 2^(-3/5)))
  
  # Covariate
  x <- runif(n, 0, 1)
  # True effect centered
  ff <- f(x) - mean(f(x))
  # Variance of the error is given by SNR 
  signal_var = var(ff)
  sigma <- sqrt(signal_var/SNR)
  # Perturbed response
  y <- ff +  rnorm(n, sd = sigma)
  
  # Output
  return(list(X = as.matrix(x),
              FF = as.matrix(ff),
              y = y))
}
```

```{r}
# Simulate data
ll = simulate.data.1(n = 500, SNR = 10)
X = ll$X
y = ll$y
FF = ll$FF

# Format the dataframe
df_long <- tibble(
  X = as.vector(X),
  FF = as.vector(FF)
) %>%
  mutate(Covariate = "Covariate 1")  # Since you only have one covariate in simulate.data.1

# Covariate plot
ggplot(df_long, aes(x = X, y = FF)) +
  geom_line(color = "grey20", linewidth = 2) +
  facet_wrap(~ Covariate, scales = "free_y") +
  theme_light(base_size = 14) +
  labs(x = NULL, y = "Value") +
  theme(
    strip.text = element_text(face = "bold", size = 12, color = "grey20"),
    strip.background = element_rect(fill = "white", color = "grey80"),
    panel.grid = element_line(color = "grey95")
  )

rm(X, y, FF)
```

# Pipeline

## Fitting function

```{r}
fitting_function = function(X_train, X_test, y_train, FF_test,
                            ndx, bdeg, lambda.init,
                            maxiter1, maxiter2, maxiter3, tol1, tol2, tol3, epsilon,
                            grid){
  
  # Nº of instances and covariates
  n = length(y_train)
  m = dim(X_train)[2]
  family = "gaussian"
  
  ## AKSSAM -------------------------------------------------------------------- 
  # Train the model
  K = vector('list', m)
  for (t in 1:m){
    K[[t]] = my.knots(X_train[,t], min(X_train[,t]), max(X_train[,t]), ndx[t], bdeg[t])
  }
  time1 <- system.time({
    model1 <- AKSSAM(X_train, y_train, family, lambda.init, ndx, bdeg, 
                     maxiter1, maxiter2, maxiter3, tol1, tol2, tol3, 
                     epsilon)
  })[3] %>% unname
  K_sel1 <- model1$K_sel
  alpha <- as.vector(model1$alpha.new)
  
  # Test
  Design_list = vector("list", m + 1)
  Design_list[[1]] = matrix(1, length(FF_test), 1) 
  for (t in 1:m){Design_list[[t+1]] = my.bbase4(X_test[,t], K_sel1[[t]], bdeg[t])}
  B_star <- do.call(cbind, Design_list) 
  predictions1 <- B_star %*% alpha
  
  # Grid
  Grid_list = vector("list", m)
  grid_basis_length = rep(0,m)
  for (t in 1:m){     
    Grid_list[[t]] = my.bbase4(grid[,t], K_sel1[[t]], bdeg[t])
    grid_basis_length[t] = dim(Grid_list[[t]])[2]
  }
  grid1 <- grid
  for (t in 1:m){
    B = Grid_list[[t]]
    if (t == 1){
      index_0 = 2
      index_1 = 1 + grid_basis_length[1]
    }else{
      index_0 = 2 + sum(grid_basis_length[1:(t-1)])
      index_1 = index_0 + grid_basis_length[t] - 1
    }
    grid1[ ,t] <- B %*% alpha[index_0:index_1]
  }
  
  # Metrics
  MSE1 <- mean((FF_test - predictions1)^2)
  MAE1 <- mean(abs(FF_test - predictions1))
  EDF1 <- Size1 <- ncol(B_star)
  
  Old_Design_list = vector("list", m + 1)
  Old_Design_list[[1]] = matrix(1, length(y_train), 1)
  for (t in 1:m){Old_Design_list[[t+1]] = my.bbase4(X_train[,t], K_sel1[[t]], bdeg[t])}
  B_star_old <- do.call(cbind, Old_Design_list)
  residuals_train <- (y_train - B_star_old %*% alpha)
  sigma2_hat <- mean(residuals_train^2)
  loglik <- -0.5 * n * log(2 * pi * sigma2_hat) - 0.5 * sum(residuals_train^2) / sigma2_hat
  AIC1 <- -2 * loglik + 2 * EDF1
  BIC1 <- -2 * loglik + log(n) * EDF1
  
  
  ## PSO algorithm   -----------------------------------------------------------
  # Train the model
  data <- data.frame(y = y_train, as.data.frame(X_train))
  terms <- paste0("s(V", 1:m, ", bs = 'cr', k = ", ndx + bdeg + 1, ")")             
  formula <- as.formula(paste("y ~", paste(terms, collapse = " + ")))
  initial_gam_model <- mgcv::gam(formula, data = data)
  time2 <- system.time({
    result <- suppressMessages(
      fit_gam_pso(
        gam_model = initial_gam_model,
        data = data,
        n_knots = ndx + bdeg + 1,
        alpha = 1e-07,
        smoothing_method = "GCV.Cp",
        max_iterations = 100
      )
    )
  })[3] %>% unname
  model2 <- result$model
  K_sel2 <- result$knots$`1`
  
  # Test
  test = as.data.frame(X_test)
  predictions2 <- as.vector(predict(model2, newdata = test))
    
  # Grid
  grid2 <- predict(model2, newdata = as.data.frame(grid), type = "terms")
  
  # Metrics
  MSE2 <- mean((FF_test - predictions2)^2)
  MAE2 <- mean(abs(FF_test - predictions2))
  EDF2 <- sum(model2$edf)
  Size2 <- length(model2$coefficients)
  
  residuals_train <- (y_train - predict(model2))
  sigma2_hat <- mean(residuals_train^2)
  loglik <- -0.5 * n * log(2 * pi * sigma2_hat) - 0.5 * sum(residuals_train^2) / sigma2_hat
  AIC2 <- -2 * loglik + 2 * EDF2
  BIC2 <- -2 * loglik + log(n) * EDF2
  
  
  ## P-splines   ---------------------------------------------------------------
  # Train the model
  terms <- paste0("s(V", 1:m, ", bs = 'ps', k = ", ndx + bdeg + 1, ")")             
  formula <- as.formula(paste("y ~", paste(terms, collapse = " + ")))
  time3 <- system.time({
    model3 <- mgcv::gam(formula, data = data, method = "REML")
  })[3] %>% unname
  
  # Test
  predictions3 <- as.vector(predict(model3, newdata = test))
    
  # Grid
  grid3 <- predict(model3, newdata = as.data.frame(grid), type = "terms")
  
  # Metrics
  MSE3 <- mean((FF_test - predictions3)^2)
  MAE3 <- mean(abs(FF_test - predictions3))
  EDF3 <- sum(model3$edf)
  Size3 <- length(model3$coefficients)
  
  residuals_train <- (y_train - predict(model3))
  sigma2_hat <- mean(residuals_train^2)
  loglik <- -0.5 * n * log(2 * pi * sigma2_hat) - 0.5 * sum(residuals_train^2) / sigma2_hat
  AIC3 <- -2 * loglik + 2 * EDF3
  BIC3 <- -2 * loglik + log(n) * EDF3
  
  ## A-splines   ---------------------------------------------------------------
  # Train the model
  k <- ndx + bdeg + 1
  X_train_vect <- as.vector(X_train)
  ordering <- order(X_train_vect)
  X_train_vect_sorted <- X_train_vect[ordering]
  y_sorted <- y_train[ordering]
  knots <- seq(min(X_train_vect), max(X_train_vect), length = k + 2)[-c(1, k + 2)]
  pen <- 10 ^ seq(-4, 4, 0.25)
  time4 <- system.time({
    aridge <- suppressWarnings(aspline(X_train_vect_sorted, y_sorted, knots, pen, degree = 3))
  })[3] %>% unname
  K_sel4 <- aridge$knots_sel[[which.min(aridge$ebic)]]
  B_train <- bSpline(X_train_vect, knots = K_sel4, degree = 3, intercept = TRUE)
  colnames(B_train) <- paste0("bs", seq_len(ncol(B_train)))
  df_train <- data.frame(y = y_train, B_train)
  model4 <- lm(y ~ ., data = df_train)
  
  # Test
  X_test_vec  <- as.vector(X_test)
  B_test <- bSpline(X_test_vec, knots = K_sel4, degree = 3, intercept = TRUE)
  colnames(B_test) <- colnames(B_train)
  df_test <- as.data.frame(B_test)
  predictions4 <- as.vector(predict(model4, newdata = df_test))
    
  # Grid
  B_grid <- bSpline(grid, knots = K_sel4, degree = 3, intercept = TRUE)
  colnames(B_grid) <- colnames(B_train) 
  df_grid <- as.data.frame(B_grid)
  grid4 <- predict(model4, newdata = df_grid) %>% as.matrix
  
  # Metrics
  MSE4 <- mean((FF_test - predictions4)^2)
  MAE4 <- mean(abs(FF_test - predictions4))
  EDF4 <- Size4 <- length(model4$coefficients)
  
  residuals_train <- (y_train - predict(model4))
  sigma2_hat <- mean(residuals_train^2)
  loglik <- -0.5 * n * log(2 * pi * sigma2_hat) - 0.5 * sum(residuals_train^2) / sigma2_hat
  AIC4 <- -2 * loglik + 2 * EDF4
  BIC4 <- -2 * loglik + log(n) * EDF4
  
  
  ## Assignment   --------------------------------------------------------------
  return(list(
    # AKSSAM algorithm results
    AKSSAM = list(MSE = MSE1,
                  MAE = MAE1,
                  Grid = grid1,
                  K_sel = K_sel1,
                  EDF = EDF1,
                  Size = Size1,
                  AIC = AIC1,
                  BIC = BIC1,
                  Time = time1),
    # PSO algorithm results
    PSO = list(MSE = MSE2,
               MAE = MAE2,
               Grid = grid2,
               K_sel = list(K_sel2),
               EDF = EDF2,
               Size = Size2,
               AIC = AIC2,
               BIC = BIC2,
               Time = time2),
    # P-splines algorithm results
    PSplines = list(MSE = MSE3,
                    MAE = MAE3,
                    Grid = grid3,
                    EDF = EDF3,
                    Size = Size3,
                    AIC = AIC3,
                    BIC = BIC3,
                    Time = time3),
    # A-splines algorithm results
    ASplines = list(MSE = MSE4, 
                    MAE = MAE4,
                    Grid = grid4,
                    K_sel = list(K_sel4),
                    EDF = EDF4,
                    Size = Size4,
                    AIC = AIC4,
                    BIC = BIC4,
                    Time = time4)
              ))
}
```


## Covariates Plot

```{r}
covariates_plot <- function(Results, grid, m, N, n, SNR){
  
  ## True covariates's effects and X
  ll = simulate.data.1(n, SNR)
  X = ll$X
  FF = ll$FF
  
  ## Miscellanea
  methods <- c('AKSSAM', 'PSO', 'P-splines', 'A-splines')
  colors <- c("True effect" = "grey50", "AKSSAM" = "#F8766D", "PSO" = "#7CAE00", "P-splines" = "#00BFC4", "A-splines" = "#C77CFF")
        
  
  ## Calculate the mean estimated covariates' effects over the simulations
  # AKSSAM algorithm
  Grid_AKSSAM_matrices <- lapply(Results, function(x) x$AKSSAM$Grid)
  mean_Grid_AKSSAM <- Reduce("+", Grid_AKSSAM_matrices) / N
  temp <- lapply(Results, function(x) x$AKSSAM$K_sel)
  K_sel_AKSSAM <- lapply(1:m, function(i){
    unlist(lapply(1:N, function(t){
      v <- temp[[t]][[i]]
      return(v[5:(length(v)-4)])
    }))
  })
  
  # PSO algorithm
  Grid_PSO_matrices <- lapply(Results, function(x) x$PSO$Grid)
  mean_Grid_PSO <- Reduce("+", Grid_PSO_matrices) / N
  temp <- lapply(Results, function(x) x$PSO$K_sel) 
  K_sel_PSO <- lapply(1:m, function(i){
    unlist(lapply(1:N, function(t){
      v <- temp[[t]][[i]]
      return(v[2:(length(v)-1)])
    }))
  })
  
  # P-Splines
  Grid_Psp_matrices <- lapply(Results, function(x) x$PSplines$Grid)
  mean_Grid_Psp <- Reduce("+", Grid_Psp_matrices) / N
  
  # A-Splines
  Grid_Asp_matrices <- lapply(Results, function(x) x$ASplines$Grid)
  mean_Grid_Asp <- Reduce("+", Grid_Asp_matrices) / N
  temp <- lapply(Results, function(x) x$ASplines$K_sel)
  K_sel_Asp <- lapply(1:m, function(i){
    unlist(lapply(1:N, function(t) temp[[t]][[i]]))
  })
  
  # Combined grids
  mean_grids <- list(
    "AKSSAM" = mean_Grid_AKSSAM,
    "PSO" = mean_Grid_PSO,
    "P-splines" = mean_Grid_Psp,
    "A-splines" = mean_Grid_Asp
  )

  
  ## Marginalized covariates' effects
  plot_list <- vector('list', m)
  plot_list <- lapply(1:m, function(t) {
    
    
    plot_df <- do.call(rbind, lapply(methods, function(method) {
      data.frame(
        x = grid[, t],
        y = mean_grids[[method]][, t],
        Method = method
      )
    }))
    o <- order(X[, t])
    true_df <- data.frame(
      x = X[o, t],
      y = FF[o, t],
      Method = "True effect"
    )
    plot_df <- rbind(plot_df, true_df)
    plot_df$Method <- factor(plot_df$Method,
                         levels = c("P-splines", "A-splines", "PSO", "AKSSAM", "True effect"))


    rug_df_AKSSAM <- data.frame(x = K_sel_AKSSAM[[t]])
    rug_df_PSO <- data.frame(x = K_sel_PSO[[t]])
    rug_df_Asp <- data.frame(x = K_sel_Asp[[t]])
    
    y_range <- range(plot_df$y, na.rm = TRUE)
    y_min <- y_range[1]
    y_max <- y_range[2]
    y_base <- y_min - 0.4 * (y_max - y_min)
    dy <- (y_max - y_min) * 0.07
    
    rug_df_AKSSAM$ymin <- y_base + 2*dy
    rug_df_AKSSAM$ymax <- y_base + 3*dy
    
    rug_df_PSO$ymin <- y_base
    rug_df_PSO$ymax <- y_base + dy
    
    rug_df_Asp$ymin <- y_base + dy
    rug_df_Asp$ymax <- y_base + 2*dy
    
    plot <- ggplot(plot_df, aes(x = x, y = y, color = Method)) +
      geom_line(linewidth = 3, alpha = 0.6, data = subset(plot_df, Method == "True effect")) +
      geom_line(linewidth = 1.1, alpha = 0.8, data = subset(plot_df, Method != "True effect")) +
      # 'Density' of selected knots
      geom_segment(data = rug_df_AKSSAM,
                   aes(x = x, xend = x, y = ymin, yend = ymax),
                   color = "#F8766D", linewidth = 2, alpha = 2/N) +
    geom_segment(data = rug_df_PSO,
                 aes(x = x, xend = x, y = ymin, yend = ymax),
                 color = "#7CAE00", linewidth = 2, alpha = 2/N) +
    geom_segment(data = rug_df_Asp,
                 aes(x = x, xend = x, y = ymin, yend = ymax),
                 color = "#C77CFF", linewidth = 2, alpha = 2/N) +
      scale_color_manual(values = colors) +
      theme_minimal() +
      scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
      labs(title = paste0('Covariate ', t),
           color = 'Curve') +
      theme_light() + 
      theme(
        legend.position = "bottom",
        axis.title = element_blank(),
        panel.grid.minor = element_blank()
      )

      return(plot)
  })
  
  
  ## Combine the plots
  combined <- wrap_plots(plot_list, nrow = 1, guides = "collect") +
  plot_annotation(
    title = paste0("SpaHet Simulation, n = ", n, ", SNR = ", SNR),
    theme = theme(
      plot.title = element_text(size = 15, face = "bold"),
      legend.position = "bottom",
      legend.direction = "horizontal",
      legend.background = element_rect(fill = alpha("white", 0.7), color = NA)
    )
  )
  
  ## Output
  return(combined)
}
```


## Error Plot

```{r}
error_plot <- function(Results){
  
  methods <- c("AKSSAM", "PSO", "PSplines", "ASplines")
  metrics <- c("MSE", "MAE", "EDF", "Size", "Time", "BIC")
  metric_labels <- c("MSE", "MAE", "EDF", "Basis Size", "Time", "BIC")
  
  all_data <- list()
  for (method in methods) {
    for (metric in metrics) {
      values <- sapply(Results, function(x) x[[method]][[metric]])
      temp_df <- data.frame(
        Value = values,
        Metric = metric,
        Method = method
      )
      all_data[[paste0(method, "_", metric)]] <- temp_df
    }
  }
  df <- bind_rows(all_data)
  df$Metric <- recode_factor(df$Metric,
    MSE = "MSE",
    MAE = "MAE",
    EDF = "EDF",
    Size = "Basis Size",
    Time = "Time",
    BIC = "BIC"
  )
  df$Metric <- factor(df$Metric, levels = metric_labels)
  df$Metric <- factor(df$Metric, levels = c("MSE", "MAE", "Time", "EDF", "Basis Size", "BIC"))
  
  df$Method <- recode(df$Method,
    "PSplines" = "P-splines",
    "ASplines" = "A-splines"
  )
  method_colors <- c(
    "AKSSAM"   = "#F8766D",
    "PSO"      = "#7CAE00",
    "P-splines" = "#00BFC4",
    "A-splines" = "#C77CFF"
  )
  
  # Boxplot of all performance metrics
  Performance_plot <- ggplot(df, aes(x = Method, y = Value, color = Method)) +
    geom_boxplot(position = position_dodge(0.75), width = 0.6, fill = NA) +
    facet_wrap(~ Metric, scales = "free_y") +
    scale_color_manual(values = method_colors) +
    labs(title = "Performance Metrics",
         x = "Method", y = "Value", color = "Algorithm") +
    theme_light(base_size = 14) +
    theme(
      legend.position = "bottom",
      legend.direction = "horizontal",
      legend.title = element_text(size = 12),
      legend.text = element_text(size = 10),
      axis.text.x = element_text(size = 8),
    )

  
  ## Output
  return(Performance_plot)
}
```


## Wrapper

```{r}
wrapper_function = function(N, n, SNR, 
                            maxiter1, maxiter2, maxiter3, tol1, tol2, tol3, epsilon,
                            ndx, bdeg, lambda.init){
  
  # Set seed for reproducibility
  set.seed(12345)
  m <- 1
  
  # List which contains the metrics for each simulation
  Results <- rep(list(
    list(
      AKSSAM = list(MSE = NA, MAE = NA, Grid = NA, K_sel = vector("list", m),
                    EDF = NA, Size = NA, AIC = NA, BIC = NA, Time = NA),
      PSO    = list(MSE = NA, MAE = NA, Grid = NA, K_sel = vector("list", m),
                    EDF = NA, Size = NA, AIC = NA, BIC = NA, Time = NA),
      PSplines = list(MSE = NA, MAE = NA, Grid = NA,
                      EDF = NA, Size = NA, AIC = NA, BIC = NA, Time = NA),
      ASplines = list(MSE = NA, MAE = NA, Grid = NA, K_sel = vector("list", m),
                      EDF = NA, Size = NA, AIC = NA, BIC = NA, Time = NA)
    )
  ), N)
  
  ## Create evaluation grid
  grid <- sapply(1:m, function(j) seq(0, 1, length.out = 100)) %>% as.matrix
  
  
  ## Loop which performs N simulations
  i <- 1
  try_tolerance <- 3 # Tolerance for retries before aborting (2 tries)
  try_attempts <- 0  # Nº of attempts
  total_fails <- 0   # Total Nº of fails
  while (i <= N) {
    
    # Simulate once the situation with error handling
    try_result <- try({
      # Simulate the data
      data <- simulate.data.1(n, SNR) 
      X_train <- X_test <- data$X
      y_train <- data$y
      FF_test <- data$FF
      # Fit the models
      result <- fitting_function(X_train, X_test, y_train, FF_test,
                                 ndx, bdeg, lambda.init,
                                 maxiter1, maxiter2, maxiter3, tol1, tol2, tol3, epsilon,
                                 grid)
      
      # Store the result, increase index and restart try_attempts
      Results[[i]] <- result
      print(paste('Simulataion ', i, 'done.'))
      i <- i + 1
      try_attempts <- 0
    }, silent = FALSE)
    
    # Error handling
    if (inherits(try_result, "try-error")) {
      # Increase try_attempts
      try_attempts <- try_attempts + 1
      total_fails <- total_fails + 1
      print(paste('try_attempt:', try_attempts))
    }
    
    # Check if the attempt tolerance is met
    if (try_attempts == try_tolerance){
      warning('Simulation error: Attempt tolerance met \n')
      break
    }
  }


  ## Output
  return(Results)
  
}
```


## Processing Function

```{r}
process_function <- function(Results, N, n, SNR){
  
  ## Miscelanea
  m <- 1
  grid <- sapply(1:m, function(j) seq(0, 1, length.out = 100)) %>% as.matrix
  
  ## Covariates estimated effect plot 
  cov_plot <- covariates_plot(Results, grid, m, N, n, SNR)
  
  
  ## Error metrics plot and values
  err_plot <- error_plot(Results)
  
  methods <- c("AKSSAM", "PSO", "PSplines", "ASplines")
  metrics <- c("MSE", "MAE", "AIC", "BIC", "EDF", "Size", "Time")
  
  err_metrics <- list()
  for (method in methods) {
    for (metric in metrics) {
      key_mean <- paste0("mean_", metric, "_", method)
      key_sd   <- paste0("sd_", metric, "_", method)
      
      values <- sapply(Results, function(x) {
        x[[method]][[metric]]
      })
      
      err_metrics[[key_mean]] <- mean(values, na.rm = TRUE)
      err_metrics[[key_sd]]   <- sd(values, na.rm = TRUE)
    }
  }
  
  ## Output
  return(list(covariates_plot = cov_plot,        # Covariates estimated effect plot 
              err_plot = err_plot,               # Error metrics plot
              err_metrics = err_metrics          # Error metrics
              ))
}
```


# Simulations

## n = 300

### SNR = 1

```{r Simulation n 300 SNR 1}
ll_n300_SNR1 <- wrapper_function(N = 100, n = 300, SNR = 1, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 300 SNR 1, eval = FALSE}
results_n300_SNR1 <- process_function(Results = ll_n300_SNR1, N = 100, n = 300, SNR = 1)
```


### SNR = 2

```{r Simulation n 300 SNR 2}
ll_n300_SNR2 <- wrapper_function(N = 100, n = 300, SNR = 2, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 300 SNR 2, eval = FALSE}
results_n300_SNR2 <- process_function(Results = ll_n300_SNR2, N=100, n=300, SNR=2)
```


### SNR = 4

```{r Simulation n 300 SNR 4}
ll_n300_SNR4 <- wrapper_function(N = 100, n = 300, SNR = 4, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 300 SNR 4, eval = FALSE}
results_n300_SNR4 <- process_function(Results = ll_n300_SNR4, N=100, n=300, SNR=4)
```


## n = 500

### SNR = 1

```{r Simulation n 500 SNR 1}
ll_n500_SNR1 <- wrapper_function(N = 100, n = 500, SNR = 1, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 500 SNR 1, eval = FALSE}
results_n500_SNR1 <- process_function(Results = ll_n500_SNR1, N = 100, n = 500, SNR = 1)
```


### SNR = 2

```{r Simulation n 500 SNR 2}
ll_n500_SNR2 <- wrapper_function(N = 100, n = 500, SNR = 2, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 500 SNR 2, eval = FALSE}
results_n500_SNR2 <- process_function(Results = ll_n500_SNR2, N = 100, n = 500, SNR = 2)
```


### SNR = 4

```{r Simulation n 500 SNR 4}
ll_n500_SNR4 <- wrapper_function(N = 100, n = 500, SNR = 4, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 500 SNR 4, eval = FALSE}
results_n500_SNR4 <- process_function(Results = ll_n500_SNR4, N = 100, n = 500, SNR = 4)
```


## n = 800

### SNR = 1

```{r Simulation n 800 SNR 1}
ll_n800_SNR1 <- wrapper_function(N = 100, n = 800, SNR = 1, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 800 SNR 1, eval = FALSE}
results_n800_SNR1 <- process_function(Results = ll_n800_SNR1, N = 100, n = 800, SNR = 1)
```


### SNR = 2

```{r Simulation n 800 SNR 2}
ll_n800_SNR2 <- wrapper_function(N = 100, n = 800, SNR = 2, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 800 SNR 2, eval = FALSE}
results_n800_SNR2 <- process_function(Results = ll_n800_SNR2, N = 100, n = 800, SNR = 2)
```


### SNR = 4

```{r Simulation n 800 SNR 4}
ll_n800_SNR4 <- wrapper_function(N = 100, n = 800, SNR = 4, 
                       maxiter1 = 100, maxiter2 = 100, maxiter3 = 100, 
                       tol1 = 1e-5, tol2 = 1e-5, tol3 = 1e-5, epsilon = 1e-5,
                       ndx = 40, bdeg = 3, lambda.init = 10)
```

```{r Processing n 800 SNR 4, eval = FALSE}
results_n800_SNR4 <- process_function(Results = ll_n800_SNR4, N = 100, n = 800, SNR = 4)
```


# Summary Table

## Full Table

```{r Summary Table, eval = FALSE}
# Initialize the table
gaussian_table = data.frame(
  n = c(rep(300, 3), rep(500, 3), rep(800, 3)), 
  SNR = rep(c(1,2,4), 3)
)

# Define indexes for n and SNR
n_vals <- c(300, 500, 800)
SNR_vals <- c(1, 2, 4)

# Iterate through all possible n and SNR combinations
row_index <- 1
for (i in 1:3) {
  for (j in 1:3) {
    # Construct object name
    obj_name <- paste0("results_n", n_vals[i], "_SNR", SNR_vals[j])
    
    # Fill the appropriate row
    gaussian_table[row_index, names(results_n800_SNR4$err_metrics)] <- get(obj_name)$err_metrics
    
    # Update the row index
    row_index <- row_index + 1
  }
}


# Format the table such that the error terms are included as mean (sd)
gaussian_table2 <- gaussian_table

# Obtain all mean columns and iterate along them
mean_cols <- grep("^mean_", names(gaussian_table), value = TRUE)
for (mean_col in mean_cols) {
  # Get the corresponding sd column
  sd_col <- sub("^mean_", "sd_", mean_col)
  # Format the column
  formatted_col <- sprintf("%.5f (%.5f)", gaussian_table[[mean_col]], gaussian_table[[sd_col]])
  gaussian_table2[[mean_col]] <- formatted_col
}
# Erase sd columns
gaussian_table2 <- gaussian_table2[ , !grepl("^sd_", names(gaussian_table2))]

# Display the Table
knitr::kable(gaussian_table2, format = "html", caption = "Mean Results for the Simualtion Scenario")


# LaTex code
xtable::xtable(gaussian_table2)
```

## Reduced table

```{r Reduced Table, eval = FALSE}
reduced_gaussian_table2 <- gaussian_table2[, c(1,2,3,4,6,7,9,10,11,13,14,15, 16,17,18,20,21,22,23,24,25,27,28,30)]

names(reduced_gaussian_table2) = c('n', 'SNR', 
                           'MSE AKSSAM', 'MAE AKSSAM', 'BIC AKSSAM', 'EDF & Size AKSSAM', 'Time AKKSAM',
                           "MSE PSO", "MAE PSO", "BIC PSO", "EDF PSO", "Size PSO", 'Time PSO',
                           "MSE P-splines", "MAE P-splines", "BIC P-splines", "EDF P-splines", "Size P-splines", 'Time P-splines',
                           'MSE A-splines', 'MAE A-splines', 'BIC A-splines', 'EDF & Size A-splines', 'Time A-splines')

# Display the Table
knitr::kable(reduced_gaussian_table2, format = "html", caption = "Mean Results for the Gaussian Scenario")


# LaTex code
xtable::xtable(reduced_gaussian_table2)
```

# Save the RData

```{r Save the data}
# Checkpoint
save.image(file = "simulation1.RData")
```






